## Problem 3
**3b and c**: Implementing Needleman-Wunsch Algorithm.

In [4]:
import numpy as np

# given two bases, determines score
def score(a, b): 
    if a == b:
        return match
    else:
        return mismatch

def needleman_wunsch(seq1, seq2):   
    # score matrix of dimension m+1 x n+1
    n = len(seq1)  
    m = len(seq2)
    
    # initialize matrix to store scores
    scores = np.zeros((m+1, n+1))
   
    # fill out first column and row with gaps
    # prevents needing to check for edge cases later in loop
    for i in range(0, m + 1):
        scores[i, 0] = gap * i
    for j in range(0, n + 1):
        scores[0, j] = gap * j
    print(scores)
    # populate the matrix with scores
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            match = scores[i - 1, j - 1] + score(seq1[j-1], seq2[i-1])
            delete = scores[i - 1, j] + gap
            insert = scores[i, j - 1] + gap
            # store the maximum score 
            scores[i, j] = max(match, delete, insert)
            print(scores)
    
    # after score matrix has been calculated, backtrack to find best alignment
    # add to a string as backtracking occurs (note that this sequence will be backwards)
    
    # start backtracking from bottom right cell
    seq1_align = ""
    seq2_align = ""
    i = m
    j = n
    # loop ends when touching the top or left edge
    while i > 0 and j > 0: 
        current = scores[i, j]
        # obtain scores from neighboring cells
        diagonal = scores[i-1, j-1]
        up = scores[i, j-1]
        left = scores[i-1, j]
        
        # find which cell produced the max score
        # either match or mismatch
        if current == diagonal + score(seq1[j-1], seq2[i-1]):
            seq1_align += seq1[j-1]
            seq2_align += seq2[i-1]
            # move diagonally
            i -= 1
            j -= 1
        # gaps: move up or left
        elif current == up + gap:
            seq1_align += seq1[j-1]
            seq2_align += '-'
            # move up
            j -= 1
        elif current == left + gap:
            seq1_align += '-'
            seq2_align += seq2[i-1]
            # move left
            i -= 1

    # add in gaps to corresponding sequence until 0, 0 is reached
    while j > 0:
        seq1_align += seq1[j-1]
        seq2_align += '-'
        j -= 1
    while i > 0:
        seq1_align += '-'
        seq2_align += seq2[i-1]
        i -= 1
    
    # backtracking created a backwards sequence -- reverse it
    seq1_align = seq1_align[::-1]
    seq2_align = seq2_align[::-1]

    return seq1_align, seq2_align, scores[m][n]

seq1 = "GATTACA"
seq2 = "AATGGACA"
match = 1
mismatch = -1
gap = -2
print(needleman_wunsch(seq1, seq2))
# match > gaps or mismatches
# finds and lists all possible alignments by varying match, mismatch and gap
'''
alignments1 = []
alignments2 = []
for i in range(-10, 10): 
    for j in range(-10, 10):
        for k in range(-10, 10):
            match = i
            mismatch = j
            gap = k
            a, b, sc = needleman_wunsch(seq1, seq2)
            if a not in alignments1:
                alignments1.append(a)
            if b not in alignments2:
                alignments2.append(b)
'''
#print(alignments1)
#print(alignments2)
#print(needleman_wunsch(seq1, seq2))

[[  0.  -2.  -4.  -6.  -8. -10. -12. -14.]
 [ -2.   0.   0.   0.   0.   0.   0.   0.]
 [ -4.   0.   0.   0.   0.   0.   0.   0.]
 [ -6.   0.   0.   0.   0.   0.   0.   0.]
 [ -8.   0.   0.   0.   0.   0.   0.   0.]
 [-10.   0.   0.   0.   0.   0.   0.   0.]
 [-12.   0.   0.   0.   0.   0.   0.   0.]
 [-14.   0.   0.   0.   0.   0.   0.   0.]
 [-16.   0.   0.   0.   0.   0.   0.   0.]]
[[  0.  -2.  -4.  -6.  -8. -10. -12. -14.]
 [ -2.  -1.   0.   0.   0.   0.   0.   0.]
 [ -4.   0.   0.   0.   0.   0.   0.   0.]
 [ -6.   0.   0.   0.   0.   0.   0.   0.]
 [ -8.   0.   0.   0.   0.   0.   0.   0.]
 [-10.   0.   0.   0.   0.   0.   0.   0.]
 [-12.   0.   0.   0.   0.   0.   0.   0.]
 [-14.   0.   0.   0.   0.   0.   0.   0.]
 [-16.   0.   0.   0.   0.   0.   0.   0.]]
[[  0.  -2.  -4.  -6.  -8. -10. -12. -14.]
 [ -2.  -1.  -1.   0.   0.   0.   0.   0.]
 [ -4.   0.   0.   0.   0.   0.   0.   0.]
 [ -6.   0.   0.   0.   0.   0.   0.   0.]
 [ -8.   0.   0.   0.   0.   0.   0.   0.]
 [-10.   

'\nalignments1 = []\nalignments2 = []\nfor i in range(-10, 10): \n    for j in range(-10, 10):\n        for k in range(-10, 10):\n            match = i\n            mismatch = j\n            gap = k\n            a, b, sc = needleman_wunsch(seq1, seq2)\n            if a not in alignments1:\n                alignments1.append(a)\n            if b not in alignments2:\n                alignments2.append(b)\n'

**3.c**:  Use your algorithm to empirically determine the average length of the longest increase subsequence in a
permutation of length 10.

In [20]:
from itertools import permutations
''''''
nums = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
p = list(permutations(nums, 10))
match = 1
mismatch = 0
gap = 0
total_len = 0
for permutation in p:
    a, b, sc = needleman_wunsch(permutation, nums)
    total_len += sc

print(total_len/len(p))


4.33496059303351


## Problem 4
Parsing of Human cDNA FASTA file using Biopython.

In [7]:
import Bio
from Bio import SeqIO

num_bases = 0
num_seq = 0
max_seq = ''
max_record = ''
# This code will not run since I did not upload the .fa file -> it is too large for the Moodle server
for seq_record in SeqIO.parse("Homo_sapiens.GRCh38.cdna.all.fa", "fasta"):
    num_bases += len(seq_record.seq)
    num_seq += 1
    if len(seq_record.seq) > len(max_seq):
        max_seq = seq_record.seq
        max_record = seq_record
print("Total amount of bases: ", num_bases)
print("Number of transcripts: ", num_seq)
print("Longest transcript: \n", max_record)

Total amount of bases:  320746109
Number of transcripts:  190432
Longest transcript: 
 ID: ENST00000589042.5
Name: ENST00000589042.5
Description: ENST00000589042.5 cdna chromosome:GRCh38:2:178525989:178807423:-1 gene:ENSG00000155657.26 gene_biotype:protein_coding transcript_biotype:protein_coding gene_symbol:TTN description:titin [Source:HGNC Symbol;Acc:HGNC:12403]
Number of features: 0
Seq('GAGCAGTCGTGCATTCCCAGCCTCGCCTCGGGTGTAGGGATTGCATAGAAAAGC...AAA', SingleLetterAlphabet())


This is the entry I picked from the Human cDNA FASTA file. 

`
ENST00000632963.1 cdna chromosome:GRCh38:CHR_HSCHR14_3_CTG1:105884674:105884693:-1 gene:ENSG00000282674.1 gene_biotype:IG_D_gene transcript_biotype:IG_D_gene gene_symbol:IGHD5-24 description:immunoglobulin heavy diversity 5-24 (non-functional) [Source:HGNC Symbol;Acc:HGNC:5510]
GTAGAGATGGCTACAATTAC
`

* ENST00000632963.1: ENCODE accession 
* cdna: the dataset of DNA
* GRCh38:CHR_HSCHR14_3_CTG1: the chromosome name
* 105884674:105884693 : indices of start and end base pairs
* -1: negative strand
* ENSG00000282674.1: Gene accession code in ENCODE datebase
* IG_D_gene: indicates the gene as immunoglobulin according to ENCODE biotypes
* IGHD5-24: shorter name for the gene
* Description provides more details about the gene, and here it labels this is non-functional. 

## Problem 5.c
Determine the most highly abundant transcript. Explain what this transcript is and what it does. Does the abundance make sense given the experiment?

In [8]:
import csv
with open("output/abundance.tsv") as fd:
    rd = csv.reader(fd, delimiter="\t", quotechar='"')
    max_count = 0
    max_id = ''
    max_row = []
    # gets rid of the first row of headers
    row = next(rd)
    # we want to use the tpm number, since it scales according to feature length
    for row in rd:
        if float(row[4]) > max_count:
            max_count = float(row[4])
            max_id = row[0]
            max_row = row
    print('ID of most abundant transcript: ', max_id)
    print('Max TPM: ',max_count)
    print(max_row)

ID of most abundant transcript:  ENSMUST00000022692.4
Max TPM:  291809.0
['ENSMUST00000022692.4', '792', '383.717', '1.43398e+006', '291809']


The most abundant transcript turned out to be Sftpc-201, which was found by looking up its gene accession ID, ENSMUST00000022692.4. According to [Ensembl](http://uswest.ensembl.org/Mus_musculus/Transcript/Summary?g=ENSMUSG00000022097;r=14:70520953-70524081;t=ENSMUST00000022692), this transcript is a surfactant associated protein. I found a [paper](https://www.nature.com/articles/s41584-018-0099-0?platform=hootsuitehttps%3A%2F%2Fwww.nature.com%2Farticles%2Fs41586-019-0889-9%3Fplatform%3Dhootsuite) relating Sftpc-201 to the SIRT1 gene described in the experient. The expression of Sftpc is necessary for correct alveolar function, and mutations to this gene result in ER stress and increased capsase activation, which triggers apoptosis. The presence of this gene makes sense, since the study focuses on lung carcinogenesis and this gene is associated with lung function.

## Problem 6 
**Extended to 4 observed states**

In [9]:
import copy

class HMM:
    def __init__(self, states, transition, emission, init):
        self.state_names = copy.copy(states)
        self.n_states = len(states)
        self.A = transition.copy()
        self.B = emission.copy()
        self.n_emissions = self.B.shape[1]
        self.init = init

    def generate(self, length):
        state = self.init
        states = []
        ret = []
        for i in range(1, length + 1):
            state = np.random.choice(range(self.n_states), p=self.A[state])
            states.append(state)
            ret.append(
                np.random.choice(range(self.n_emissions), p=self.B[state]))
        print('Generating by states:', ''.join(self.state_names[i] for i in states))
        ret = ''.join([str(i) for i in ret])
        return ret
    

    def viterbi(self, seq):
        # := max-product
        seq_arr = np.array([int(i) for i in seq])
        T = len(seq_arr)
        T1 = np.zeros((self.n_states, T + 1))
        T1[self.init, 0] = 1
        T2 = np.zeros((self.n_states, T + 1), dtype='int')
        states = np.zeros(T + 1, dtype='int')
        for t in range(1, T + 1):
            for j in range(self.n_states):
                T1[j, t] = np.max(T1[:, t - 1] * self.A[:, j])
                T1[j, t] *= self.B[j, seq_arr[t - 1]]
                T2[j, t] = np.argmax(T1[:, t - 1] * self.A[:, j])
        states[T] = np.argmax(T1[:, T])
        for t in range(T, 1, -1):
            states[t - 1] = T2[states[t], t - 1]
        return ''.join([self.state_names[s] for s in states[1:]])
    
np.random.seed(1236)
states = ['A', 'B', 'C', 'D']

print("1.1 Generation\n")
transition = np.array([
    [0.8, 0.1, 0.0, 0.1],
    [0.1, 0.5, 0.2, 0.2],
    [0.1, 0.0, 0.6, 0.3],
    [0.2, 0.3, 0.1, 0.4]
])
emission = np.array([
    [0.9, 0.1],
    [0.5, 0.5],
    [0.1, 0.9], 
    [0.2, 0.8]
])
init = 0
hmm = HMM(states, transition, emission, init)
seqs = []
for seq_len in [100, 1000, 10000]:
    seq = hmm.generate(seq_len)
    seqs.append(seq)
    print("Inferred optimal state series:")
    print(hmm.viterbi(seq))
    # NOTE: To run chains with various length, REMOVE this break
    break

1.1 Generation

Generating by states: AAAAAABBBBDCCCCDBDBBDDDDAAAAAAAADBBBCCCDDAADAABBCDAAAAADAABBCCCDBCCCCCDAAAAADBBADBBABBAAAAAAAAAAAAAA
Inferred optimal state series:
AAAAAAAAABBCCCCAAABCCCCCCCAAAAAAAAAADDDAAAAAAAAAAAAAAAAADDBBCCCCCCCCCCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
